### ISSUE TITLE
Add a difficulty level to all quests

### ISSUE THREAD

**Issue by frodare** [ToroCraft/Dailies#19]
The mod could relay the difficult to the payer using a repeated icon.  So for a hard quest, it could have 3 sword icons instead of one.

The server should only take the difficulty under consideration when selecting the next round of quests, maybe only have one hard one, one moderate and the rest easy.

**Comment by pandapaul** [comment]
Moved to service side issue:  https://github.com/pandapaul/minecraft-dailies-server/issues/10
