### ISSUE TITLE
Dailies hover GUI shows up outside of Bailey's UI

### ISSUE THREAD

**Issue by frodare** [ToroCraft/Dailies#37]

**Comment by frodare** [comment]
![logged_out_gui](https://cloud.githubusercontent.com/assets/795621/19024995/0d50cb22-88df-11e6-9f4f-329e85f14829.png)

**Comment by zeriley** [comment]
I believe they showed up elsewhere for me the other night, maybe over JourneyMap.  I'll try to reproduce at my next opportunity.

**Comment by TwitchtvCarbs** [comment]
This still happens in v6-1.11.2 D:

**Comment by pandapaul** [comment]
@Wing01 💯 👍
