### ISSUE TITLE
Unfortunately an Error has Occurred - 1.10/1.12 

### ISSUE THREAD

**Issue by Y0ungSandwich** [ToroCraft/Dailies#57]
![2017-08-29_20 20 00](https://user-images.githubusercontent.com/3539387/29849837-7c73212c-8cf7-11e7-877c-9505f59d36e4.png)

Getting this on our 1.10 version and while testing our 1.12 version

**Comment by frodare** [comment]
Should be up and running now, thanks for letting us know!
